### ISSUE TITLE
How to train models? 

### ISSUE THREAD

**Issue by digitalgopnik** [antonisa/unimorph_inflect#4]
Hello antonisa! Thanks for this great library! :) Works really great!

But i have one question: how can i train/retrain a model, build an own ```model.zip``` with ```tag.vocab```, ```char.vocab``` and ```language.model```?

Did i overlook something inside the code?

In the readme, you said:
> Install from source from this git repository will give you more flexibility in developing on top of unimorph_inflect and training your own models. For this option, run...

But what do i have to execute or do afterwards to train my own model? 

Would be nice to hear from you! 
Friendly regards

**Comment by antonisa** [comment]
Thanks for the encouraging words!

The models are built with this tool: [https://github.com/antonisa/inflection](https://github.com/antonisa/inflection) 

Apologies for the misleading comment in the readme -- I haven't introduced the training functionality in this library.

**Comment by digitalgopnik** [comment]
Got you! Thanks for your ultra quick response! :) 
Nice!
